#Generated by rpmwand v. 0.9.3 Thu Aug  2 17:00:30 CEST 2012
%define _builddir /root/rpmbuild/BUILD
%define _topdir /
%define _buildrootdir /root/rpmbuild/BUILDROOT
%define _rpmdir /root/rpmbuild/RPMS
%define _tmppath /root/rpmbuild/BUILD/tmp
%define _sourcedir /root/rpmbuild/SOURCES
%define debug_package %{nil}

Summary: Console Password Manager
Vendor: RPL
Packager: NHT
License: GPL
Group: System
URL: https://github.com/comotion/cpm/downloads

Name: cpm
Version: 0.31
Release: 1.el6
Source: %name-%version.tar.gz
BuildRoot: /root/rpmbuild/BUILDROOT
AutoReqProv: no
Requires: cdk
Requires: cracklib
Requires: cracklib-dicts
Requires: dotconf
Requires: gpgme

%description
Console Password Manager

##########################################################################################
# BUILD-TIME SCRIPTS
##########################################################################################
%prep
true "=================================================================================="
true "BEG Build preprocess"
true "END Build preprocess"

%setup -q
true "=================================================================================="
true "BEG Setup"
true "END Setup"

%build
true "=================================================================================="
true "BEG Build"
echo "BUILDROOT: %{buildroot}"
echo "BUILDROOTDIR: %{_buildrootdir}"
echo "PACKAGE-NAME: %{name}"
echo "PACKAGE-VERSION: %{version}"
echo "PACKAGE-RELEASE: %{release}"
./configure --with-cracklib-dict=/usr/share/cracklib/pw_dict --with-cdk-dir=/usr --prefix=/usr --localedir=/usr/share/locale
true "END Build"

%install
true "=================================================================================="
true "BEG Installation"
mkdir -p %{buildroot}/usr/bin
mkdir -p %{buildroot}/usr/share
mkdir -p %{buildroot}/usr/share/locale/de/LC_MESSAGES
true "END Installation"

%makeinstall localedir=${RPM_BUILD_ROOT}/usr/share/locale
true "=================================================================================="
true "BEG make install"
true BUILDROOTDIR:%{_buildrootdir}
true "END make install"

%clean
true "=================================================================================="

%files -f "/root/rpmbuild/SOURCES/cpm-files.txt"

##########################################################################################
# INSTALL/UNINSTALL-TIME SCRIPTS
##########################################################################################
%pretrans
true BEG Pre-transaction script
# Usually umask here
umask 007

%pre
true BEG Pre-installation script
if test "$1" = "1"; then # Install
	#Place your script pre-install script
	#echo "Pre-install script version:" %{version}>> /tmp/%{name}.log
	:
else # Update ($1 = "2")
	#Place your script pre-update script
	#echo "Pre-update script of new version:" %{version}>> /tmp/%{name}.log
	:
fi

true END Pre-installation script

%post
true BEG Post-installation script
if test "$1" = "1"; then # Install
	#Place your script post-install script
	#echo "Post-install script version:" %{version}>> /tmp/%{name}.log
	:
else # Update ($1 = "2")
	#Place your script post-update script
	#echo "Post-update script of new version:" %{version}>> /tmp/%{name}.log
	:
fi


true END Post-installation script

%preun
true BEG Pre-uninstall script
if test "$1" = "0"; then # Uninstall
	#Place your script pre-uninstall script
	#echo "Pre-uninstall script version:" %{version}>> /tmp/%{name}.log
	:
else # Uninstall by new version ($1 = "1")
	#Place your script pre-update script
	#echo "Pre-update script of old version:" %{version}>> /tmp/%{name}.log
	:
fi

true END Pre-uninstall script

%postun
true BEG Post-uninstall script
#Place temporary file cleaner here.
#Place user deletion script here.
if test "$1" = "0"; then # Uninstall
	#Place your script post-uninstall script
	echo "Post-uninstall script version:" %{version}>> /tmp/%{name}.log
	:
else # Uninstall by new version ($1 = "1")
	#Place your script post-update script
	echo "Post-update script of old version:" %{version}>> /tmp/%{name}.log
	:
fi

true END Post-uninstall script

%changelog

